### ISSUE TITLE
Taille du champ nomenclature de la table port_activité trop petite

### ISSUE THREAD

**Issue by Baraban35** [Baraban35/SuiviSIO#1]
Au niveau de la base de données le champ nomenclature de la table port_activité est déclaré en varchar(6) or il faut le modifier avec une longueur de 7 car la nomenclature de l'activité rédaction d'une documentation utilisateur est tronquée A4.1.1 au lieu de A4.1.10

**Comment by GDucourneau** [comment]
Modification du script de création de la structure de la table port_activite de la base portefeuille : 
( sous repertoire_de_project/dirrw/param/database.sql )
- la ligne 34 devient 
  `nomenclature` char(7) NOT NULL,
- la ligne 87 devient
  (43, 11, 'A4.1.10', 45, 'Rédaction d''une documentation d''utilisation'), 

Remarque : si l'application est déjà mise en place, il faut :
-Se connecter au serveur web avec phpmyadmin
-Sélectionner la base portefeuille
-Aller dans l'onglet SQL
-Agrandir le champ nomenclature de la table port_activite :
ALTER TABLE `port_activite` 
MODIFY `nomenclature` CHAR(7);
-Modifier la nomenclature de l'activité 43 :
UPDATE `port_activite` 
SET `nomenclature` = 'A4.1.10' 
WHERE `id` =43;
